apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipment
  labels:
    app: equipment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipment
  template:
    metadata:
      labels:
        app: equipment
    spec:
      containers:
        - name: equipment
          image: username/equipment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5